apiVersion: v1
kind: Service
metadata:
  name: mindbridge-backend
  namespace: mindbridge
spec:
  type: NodePort
  selector:
    app: mindbridge-backend
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400
